name: massiverepeat
version: 1.0.1
main: com.massivecraft.massiverepeat.P
depend: [mcore4, Vault]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massiverepeat.create: {description: create new repeat, default: op}
  massiverepeat.add: {description: create new repeat and autostart, default: op}
  massiverepeat.delete: {description: delete a repeater, default: op}
  massiverepeat.list: {description: list repeaters, default: op}
  massiverepeat.show: {description: show info on a repeater, default: op}
  massiverepeat.start: {description: start existing repeater, default: op}
  massiverepeat.restart: {description: stop then start, default: op}
  massiverepeat.pause: {description: pause repeater, default: op}
  massiverepeat.stop: {description: stop repeater a go to start, default: op}
  massiverepeat.field.cmds.list: {description: list commands in repeater, default: op}
  massiverepeat.field.cmds.add: {description: add command to repeater, default: op}
  massiverepeat.field.cmds.remove: {description: remove command from repeater, default: op}
  massiverepeat.field.cmds.clear: {description: clear commands from repeater, default: op}
  massiverepeat.field.permanent: {description: edit permanent field, default: op}
  massiverepeat.field.length: {description: edit length field, default: op}
  massiverepeat.field.pos: {description: edit pos field, default: op}
  massiverepeat.field.mindelay: {description: edit mindelay field, default: op}
  massiverepeat.field.maxdelay: {description: edit maxdelay field, default: op}
  massiverepeat.field.mininterval: {description: edit mininterval field, default: op}
  massiverepeat.field.maxinterval: {description: edit maxinterval field, default: op}
  massiverepeat.repeat.*: {description: repeat any command, default: op}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  massiverepeat.*:
    default: op
    children:
      massiverepeat.kit.most: true
      massiverepeat.repeat.*: true
  massiverepeat.field.*:
    default: false
    children:
      massiverepeat.field.cmds.*: true
      massiverepeat.field.permanent: true
      massiverepeat.field.length: true
      massiverepeat.field.pos: true
      massiverepeat.field.mindelay: true
      massiverepeat.field.maxdelay: true
      massiverepeat.field.mininterval: true
      massiverepeat.field.maxinterval: true
  massiverepeat.field.cmds.*:
    default: false
    children:
      massiverepeat.field.cmds.list: true
      massiverepeat.field.cmds.add: true
      massiverepeat.field.cmds.remove: true
      massiverepeat.field.cmds.clear: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massiverepeat.kit.most:
    default: false
    children:
      massiverepeat.create: true
      massiverepeat.add: true
      massiverepeat.delete: true
      massiverepeat.list: true
      massiverepeat.show: true
      massiverepeat.start: true
      massiverepeat.restart: true
      massiverepeat.pause: true
      massiverepeat.stop: true
      massiverepeat.field.*: true